### ISSUE TITLE
Support for PMTiles

### ISSUE THREAD

**Issue by dbreunig** [ankane/mapkick#19]
Any interest in supporting [PMTiles](https://github.com/protomaps/PMTiles) and [Protomaps](https://docs.protomaps.com/)? The ability to serve tiles from any static file server is really nice, and the Protomaps ecosystem has really matured.

**Comment by ankane** [comment]
Hi @dbreunig, looking at [the docs](https://github.com/protomaps/PMTiles/blob/main/js/README.md#maplibre-gl-js), I think there's a chance it already supports this since Mapkick.js [supports MapLibre](https://github.com/ankane/mapkick.js?tab=readme-ov-file#maplibre) (the assets just aren't included in the gem, so would need to include them manually).

**Comment by dbreunig** [comment]
Ah nice! I didn't peek at Mapkick.js. Might have to take a pass at standing up a PMTile demo later this week with the gem and see what's involved.
